# permissions for end users to edit datacollectionpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datacollectionpolicy-editor-role
rules:
- apiGroups:
  - copilot.redhataicoe.com
  resources:
  - datacollectionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - copilot.redhataicoe.com
  resources:
  - datacollectionpolicies/status
  verbs:
  - get
