# permissions for end users to view datacollectionpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datacollectionpolicy-viewer-role
rules:
- apiGroups:
  - copilot.redhataicoe.com
  resources:
  - datacollectionpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - copilot.redhataicoe.com
  resources:
  - datacollectionpolicies/status
  verbs:
  - get
