
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - copilot.redhataicoe.com
  resources:
  - datacollectionpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - copilot.redhataicoe.com
  resources:
  - datacollectionpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - copilot.redhataicoe.com
  resources:
  - datacollectionpolicies/status
  verbs:
  - get
  - patch
  - update
